package main

const INPUT_DIR = "input"
const OUPUT_PATH = "output"

var OrderOfRegions = map[string]int{
	"Incheon":    0,
	"Ansan":      1,
	"PyeongtaEK": 2,
	"Daesan":     3,
	"ANHEUNG":    4,
	"Boryeong":   5,
	"EOCHEONGDO": 6,
	"Janghang":   7,
	"Gunsan-Out": 8,
	"WIDO":       9,
	"Yeonggwang": 10,
	"Mokpo":      11,
	"HEUKSANDO":  12,
	"Jindo":      13,
	"Wando":      14,
	"GEOMUNDO":   15,
	"Goheung":    16,
	"Yeosu":      17,
	"Tongyung":   18,
	"Geojedo":    19,
	"Masan":      20,
	"Busan":      21,
	"Jeju":       22,
	"Seogipo":    23,
	"SEONGSANPO": 24,
	"MOSEULOP":   25,
	"CHUJADO":    26,
	"Ulsan":      27,
	"Pohang":     28,
	"Hupo":       29,
	"Mokho":      30,
	"Sokcho":     31,
	"Ulleungdo":  32,
}
